### ISSUE TITLE
Server stopping immediately after the module is started.

### ISSUE THREAD

**Issue by lopezchau** [lorifranke/SlicerTMS#10]
Using 3D Slicer 5.0.3 .
Macbook Pro 16GB Apple M1 Pro Chip
Monterrey 12.6.8

The server initiates normally.  As soon as a I select TMS module the server stopped and I get this message.  Any help will be appreciated.
<img width="889" alt="Captura de Pantalla 2023-09-13 a la(s) 11 35 19" src="https://github.com/lorifranke/SlicerTMS/assets/143896040/65f3a785-d0c0-4a77-b4df-affb41bfe588">

**Comment by windyjunfeng** [comment]
Well, it happened to me, too. I checked the files and  found that the size of files model.pth.tar and fibers.vtk is wrong. They are only 1kB size. So I downloaded them separately and replaced the older. Then, everything goes well. 
Maybe it's the same reason?
Click the top right button. (the right of the 'Raw' button)
![image](https://github.com/lorifranke/SlicerTMS/assets/58356387/b5d43c4d-1201-454e-9b05-b0e968ec95d1)

**Comment by lopezchau** [comment]
Thank you! Thank solved it for .vtk but still get the same error on model.pth.tar ....

**Comment by lorifranke** [comment]
@lopezchau @windyjunfeng yes, the issue here is that these files are too large for github. I uploaded them here in this repo, but here is a separate example that might work: https://drive.google.com/drive/folders/1t4bExbw3JHdDodaknVCaJNUHOacDFEuo?usp=sharing
Please put the example folder inside the data folder of SlicerTMS to the other examples. In your command line go to the server folder of the SlicerTMS module, and before stating SlicerTMS, please run `python3 server.py Example4`

**Comment by lopezchau** [comment]
> @lopezchau @windyjunfeng yes, the issue here is that these files are too large for github. I uploaded them here in this repo, but here is a separate example that might work: https://drive.google.com/drive/folders/1t4bExbw3JHdDodaknVCaJNUHOacDFEuo?usp=sharing Please put the example folder inside the data folder of SlicerTMS to the other examples. In your command line go to the server folder of the SlicerTMS module, and before stating SlicerTMS, please run `python3 server.py Example4`

Thank you so much!
