### ISSUE TITLE
Bug with 3D Slicer 5.6

### ISSUE THREAD

**Issue by lopezchau** [lorifranke/SlicerTMS#13]
Dear Team,

3D Slicer 5.6 has been released.  I tried to run the extension with it. The program crash when "Load Example" button is clicked.

**Comment by lorifranke** [comment]
@lopezchau I fixed some bugs and updated SlicerTMS which should now work with 3D Slicer version 5.6.2 revision 32448 built 2024-04-05. Please ignore the red errors in the console that due to Qt and occur with the new Slicer 5.6.2 version, SlicerTMS should work anyways when loading. I tested it here:
<img width="1438" alt="slicer_5 6 2_bugswithslicertms" src="https://github.com/lorifranke/SlicerTMS/assets/38534852/2a822c18-ac7d-424f-add4-971f24452e29">

If someone prefers to use the older slicer versions, here they are. SlicerTMS was first developed with 3DSlicer 5.0.3:
https://slicer-packages.kitware.com/#collection/5f4474d0e1d8c75dfc70547e/folder/5f4474d0e1d8c75dfc705482
